- job:
    name: gluster-ansible-infra/firewall_config
    node: gluster
    description: Run the test against a bare docker container and check if role
      firewall_config is working fine.
    
    scm:
    - git:
        url: https://github.com/gluster/centosci.git
        branches:
        - origin/master

    properties:
    - github:
        url: https://github.com/gluster/gluster-ansible-infra/tree/master/roles/firewall_config

    builders:
    - shell: !include-raw: scripts/common/get-node.sh
    - shell: scripts/common/bootstrap.sh $WORKSPACE/scripts/gluster-ansible-infra/infra_firewall_config.sh

    publishers:
    - post-tasks:
        - matches:
            - log-text: Firewall configured
          script:
            !include-raw: scripts/common/return-node.sh

